# Generated by Django 3.1.4 on 2021-12-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taks', '0002_auto_20211212_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
